package com.spring.app.enums;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

@RequiredArgsConstructor
public enum EPermission {
  ADMIN_READ("PERMISSION_ADMIN_READ"),
  ADMIN_UPDATE("PERMISSION_ADMIN_UPDATE"),
  ADMIN_CREATE("PERMISSION_ADMIN_CREATE"),
  ADMIN_DELETE("PERMISSION_ADMIN_DELETE"),
  MANAGER_READ("PERMISSION_MANAGER_READ"),
  MANAGER_UPDATE("PERMISSION_MANAGER_UPDATE"),
  MANAGER_CREATE("PERMISSION_MANAGER_CREATE"),
  MANAGER_DELETE("PERMISSION_MANAGER_DELETE"),
  ;

  @Getter
  private final String permission;
}
