# ===============================
# = MySQL DataSource
# ===============================
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_test_spring?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver

  # ===============================
  # = Hibernate JPA
  # ===============================
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC
    open-in-view: false

  # ===============================
  # = Flyway
  # ===============================
  flyway:
    baseline-on-migrate: true
    enabled: false
    baseline-description: "initial"
    baseline-version: 1
    locations: classpath:db/migrations

  # ===============================
  # = Upload config
  # ===============================
  file:
    storage:
      upload-dir: uploads
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  # ===============================
  # = Redis config
  # ===============================
  data:
    redis:
      host: localhost
      port: 6379
      password:
      timeout: 60000

  # ===============================
  # = Mail config
  # ===============================
  mail:
    app: SPRING_APP
    host: smtp.gmail.com
    port: 587
    from:
    username:
    password:
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
    default-encoding: UTF-8

  # ===============================
  # = OAuth2 Google config
  # ===============================
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
            scope: openid,email,profile
            redirect-uri: http://localhost:8080/api/v1/auth/oauth2/code/google
        provider:
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub

  # ===============================
  # = Spring Cloud Compatibility
  # ===============================
  cloud:
    compatibility-verifier:
      enabled: false

  # ===============================
  # = Application Name
  # ===============================
  application:
    name: springapp

# ===============================
# = Jwt config
# ===============================
application:
  security:
    jwt:
      secret-key:
      expiration: 86400000
      refresh-token:
        expiration: 604800000

# ===============================
# = Rate Limiting Configuration
# ===============================
app:
  rate-limit:
    # Global rate limiting
    global:
      enabled: true
      requests-per-minute: 100
      requests-per-hour: 1000
      requests-per-day: 10000
      burst-capacity: 200

    # Authentication rate limiting
    auth:
      enabled: true
      requests-per-minute: 10
      requests-per-hour: 100
      requests-per-day: 1000
      burst-capacity: 20

    # Upload rate limiting
    upload:
      enabled: true
      requests-per-minute: 5
      requests-per-hour: 50
      requests-per-day: 500
      burst-capacity: 10

    # API rate limiting
    api:
      enabled: true
      requests-per-minute: 60
      requests-per-hour: 600
      requests-per-day: 6000
      burst-capacity: 100
